// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_API_Project.Data;

#nullable disable

namespace REST_API_Project.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("REST_API_Project.Models.Errand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Errands");
                });

            modelBuilder.Entity("REST_API_Project.Models.ErrandWorker", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.Property<int>("ErrandId")
                        .HasColumnType("int");

                    b.HasKey("WorkerId", "ErrandId");

                    b.HasIndex("ErrandId");

                    b.ToTable("ErrandWorkers");
                });

            modelBuilder.Entity("REST_API_Project.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("REST_API_Project.Models.ErrandWorker", b =>
                {
                    b.HasOne("REST_API_Project.Models.Errand", "Errand")
                        .WithMany("ErrandWorkers")
                        .HasForeignKey("ErrandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("REST_API_Project.Models.Worker", "Worker")
                        .WithMany("ErrandWorkers")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Errand");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("REST_API_Project.Models.Errand", b =>
                {
                    b.Navigation("ErrandWorkers");
                });

            modelBuilder.Entity("REST_API_Project.Models.Worker", b =>
                {
                    b.Navigation("ErrandWorkers");
                });
#pragma warning restore 612, 618
        }
    }
}
